### ISSUE TITLE
Decide on decision-making

### ISSUE THREAD

**Issue by eallenOP** [OtagoPolytechnic/D4LS#1]
How will we record decisions that need to be made and people's contributions towards them?

**Comment by eallenOP** [comment]
Perhaps we should just use this? That way it's in the same place as the documentation, people can assign themselves if necessary, and we can mark stuff as closed when the decision is made.

**Comment by tclark** [comment]
1.  Props for being incredibly meta.
2.  We need to get the whole team on here, as of right now only four of us are in the GitHub team.

**Comment by eallenOP** [comment]
1. Thanks, I think that's how I ended up being labelled "task manager".
2. #2

**Comment by tclark** [comment]
I think we have this sorted.  Basic discussion and the occasional quick issue will be handled on Slack.  We'll use the issue tracker for larger tasks.
